### ISSUE TITLE
Executing a slow command in k8s pod faces a timeout error

### ISSUE THREAD

**Issue by mojtaba-esk** [celestiaorg/knuu#213]
Executing a slow command in k8s pod faces a timeout error. 
Even though `ExecuteCommandWithContext` is added to `knuu`, it seems like there is another time limitation for executing commands inside an instance.

How to reproduce:

in [knuu-example](https://github.com/celestiaorg/knuu-example), open [/basic/bittwister_test.go](https://github.com/celestiaorg/knuu-example/blob/main/basic/bittwister_test.go) and in `func TestBittwister_Bandwidth(t *testing.T) ` function, change the `iperfTestDuration` constant to a larger number like `120`:

```go
	const (
		iperfTestDuration    = 120 * time.Second
		iperfParallelClients = 4
		commandTimeout       = 60 * time.Minute
	)
```

Then run the following test:
```bash
go test -v ./basic --run=TestBittwister_Bandwidth
```

Since the test takes a long time, it seems like the underlying k8s API cuts off the execution if it takes more than 10 minutes. Here is some logs:

```logs
...
bittwister_test.go:126: Starting bandwidth test. It takes a while.
panic: test timed out after 10m0s
running tests:
	TestBittwister_Bandwidth (10m0s)
	TestBittwister_Bandwidth/8_Mbps (21s)

goroutine 360 [running]:
testing.(*M).startAlarm.func1()
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.tRunner.func1()
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc0004541a0, 0xc00059db38)
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/testing/testing.go:1601 +0x138
testing.runTests(0xc0000cd540?, {0x2509d20, 0x9, 0x9}, {0x59?, 0xc0000c8cf0?, 0x251eb60?})
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc0000cd540)
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/testing/testing.go:1925 +0x636
github.com/celestiaorg/knuu-example/basic.TestMain(0x472f5a?)
	/home/moji/celestia/knuu-example/basic/main_test.go:21 +0x1cf
main.main()
	_testmain.go:65 +0x1c6

goroutine 11 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000041da0)
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/util/workqueue/delaying_queue.go:276 +0x305
created by k8s.io/client-go/util/workqueue.newDelayingQueue in goroutine 1
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/util/workqueue/delaying_queue.go:113 +0x21f

goroutine 12 [chan receive, 10 minutes]:
k8s.io/client-go/transport.(*dynamicClientCert).Run(0xc0001966c0, 0xc000050660)
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cert_rotation.go:147 +0x2a9
created by k8s.io/client-go/transport.(*tlsTransportCache).get in goroutine 1
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cache.go:122 +0x594

goroutine 25 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000196690, 0x2)
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/runtime/sema.go:527 +0x159
sync.(*Cond).Wait(0x19a3470?)
	/home/moji/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64/src/sync/cond.go:70 +0x85
k8s.io/client-go/util/workqueue.(*Type).Get(0xc000041c80)
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/util/workqueue/queue.go:200 +0x99
k8s.io/client-go/transport.(*dynamicClientCert).processNextWorkItem(0xc0001966c0)
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cert_rotation.go:156 +0x47
k8s.io/client-go/transport.(*dynamicClientCert).runWorker(...)
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cert_rotation.go:151
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xa00000000?, {0x19a7940, 0xc00051e000}, 0x1, 0xc000050660)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0xc00028ee40?, 0x1?, 0x2?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/backoff.go:161 +0x1e
created by k8s.io/client-go/transport.(*dynamicClientCert).Run in goroutine 12
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cert_rotation.go:140 +0x1ef

goroutine 26 [select]:
k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x19bc748, 0xc000050660}, 0xc00029df50, 0x5?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/wait.go:205 +0xd7
k8s.io/apimachinery/pkg/util/wait.poll({0x19bc748, 0xc000050660}, 0x0?, 0x0?, 0x0?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:260 +0x89
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x19bc748?, 0xc000050660?}, 0x0?, 0x0?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:200 +0x53
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x8?, 0x8?, 0x400000000?)
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:187 +0x3c
created by k8s.io/client-go/transport.(*dynamicClientCert).Run in goroutine 12
	/home/moji/go/pkg/mod/k8s.io/client-go@v0.28.3/transport/cert_rotation.go:142 +0x29a

goroutine 27 [select]:
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext.poller.func1.1()
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:297 +0x1c5
created by k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext.poller.func1 in goroutine 26
	/home/moji/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:280 +0xc5

```

**Comment by smuu** [comment]
I also had `panic: test timed out after 10m0s` before.
This is due to the Go test default timeout of 10 min. You can change that by using the parameter `-timeout <time>` (e.g. `-timeout 30m`).

**Comment by mojtaba-esk** [comment]
> I also had `panic: test timed out after 10m0s` before. This is due to the Go test default timeout of 10 min. You can change that by using the parameter `-timeout <time>` (e.g. `-timeout 30m`).

Thanks, I will try that out

**Comment by smuu** [comment]
@smuu to check

Ref.: https://github.com/celestiaorg/knuu-example/actions/runs/7287842247/job/20339130416#step:5:634
