### ISSUE TITLE
PortForward crashing

### ISSUE THREAD

**Issue by tty47** [celestiaorg/knuu#327]
we are facing some issues since the refactor:

```
-103445
DEBU[2024-05-08T10:34:50+02:00]knuu/instance_helper.go:145 Started statefulSet 'val0-a98e15e8'
DEBU[2024-05-08T10:34:50+02:00]knuu/instance_helper.go:146 Set state of instance 'val0-a98e15e8' to 'Committed'
DEBU[2024-05-08T10:34:50+02:00]knuu/instance.go:1074 Set state of instance 'val0-a98e15e8' to 'Started'
DEBU[2024-05-08T10:35:06+02:00]k8s/k8s_pod.go:282 Port forwarding from 63900 to 26657
DEBU[2024-05-08T10:35:06+02:00]k8s/k8s_pod.go:283 Port forwarding stdout: {[] 0 0}
DEBU[2024-05-08T10:35:06+02:00]k8s/k8s_pod.go:298 Port forwarding ready from 63900 to 26657
DEBU[2024-05-08T10:35:06+02:00]knuu/instance.go:1318 Set state of instance 'val0-a98e15e8' to 'Stopped'
{"level":"error","error":"error destroying pod for instance 'val0-a98e15e8': failed to delete service account: serviceaccounts \"val0-a98e15e8\" not found","name":"val0","time":"2024-05-08T10:35:07+02:00","message":"node  failed to cleanup"}
panic: close of closed channel

goroutine 1 [running]:
github.com/celestiaorg/knuu/pkg/k8s.(*Client).PortForwardPod.func1()
```

PR to revert the chagnes: https://github.com/celestiaorg/knuu/pull/326

**Comment by smuu** [comment]
we use proxy now
